console.log ("Nome") ; console.log ("Danielle")
console.log ("Email") ; console.log ("dany_gtolentino@outlook.com")
console.log ("Profissão") ; console.log ("Pedagoga")
console.log ("Idade") ; console.log ("41")
console.log ("Pais dos Sonhos") ; console.log ("Italia")
